/// Flutter icons ExtraIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExtraIcons
///      fonts:
///       - asset: fonts/ExtraIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ExtraIcons {
  ExtraIcons._();

  static const _kFontFam = 'ExtraIcons';
  static const String _kFontPkg = null;

  static const IconData i7343297131581665305 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg); // plant
  static const IconData i12197822711553169543 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg); // shaking fist
  static const IconData i3979643181582000622 =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg); // helping hands
  static const IconData i12389786231582000618 =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg); // heart hands
  static const IconData i9741883171561032669 =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg); // ig big
  static const IconData i18265738341599780998 =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg); // ig small
  static const IconData i20128634341559031671 =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);  // fb
  static const IconData fist_raised =
      IconData(0xf6de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
